services:
  mongo:
    image: mongo:7.0.28-jammy@sha256:88785f6f665ab817955ec1cb4f05b7b9c76947023086401413085cd1fff091a4
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data-v7-jammy:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongo-data-v7-jammy:
